# Generated by Django 4.2.1 on 2024-12-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_website_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='type',
            field=models.CharField(blank=True, choices=[('PROXY', 'PROXY'), ('SEARCH', 'SEARCH'), ('CONTENT', 'CONTENT')], max_length=30, null=True),
        ),
    ]
