# Generated by Django 4.2.1 on 2024-11-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='xml_data',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
