# Generated by Django 4.2.1 on 2024-11-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_advertisement_add_id_advertisement_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='sub_title_1',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='sub_title_2',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
